services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      # Mount the shared volume where updater places the archive data and index.json
      - archive_data:/usr/share/nginx/html/archive
      - archive_data:/usr/share/nginx/html/app/public # Mount for index.json

  updater:
    entrypoint: ["/bin/bash", "-c", "./scripts/update-archive.sh"]
    build:
      context: .
      dockerfile: Dockerfile.updater
    environment:
      # Use environment variables directly, which can be sourced from .env
      ARCHIVE_REPO_URL: ${ARCHIVE_REPO_URL:-https://github.com/YOUR_GITHUB_USERNAME/YOUR_ARCHIVE_REPO.git}
      UPDATE_INTERVAL_SECONDS: ${UPDATE_INTERVAL_SECONDS:-3600} # 1 hour, can be overridden
    volumes:
      # Mount the same shared volume
      - archive_data:/archive-data # Where updater clones the repo
      - archive_data:/app/app/public # Where updater generates index.json
    # Restart policy to ensure updater keeps running
    restart: unless-stopped

volumes:
  archive_data:
